services:
  db:
    container_name: contacts_db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contacts_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: contacts_app
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: contacts_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: contacts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
